mesh_modifiers:
  - name: CleanData
  - name: FillHoles
    max_hole_size: 0.03        # m, set to your largest dropout
  - name: WindowedSincSmoothing
    num_iter: 100
    enable_boundary_smoothing: true
    enable_feature_edge_smoothing: false
    enable_non_manifold_smoothing: true
    enable_normalize_coordinates: true
    feature_angle: 10.0
    edge_angle: 150.0
    pass_band: 0.01